sudo: false

language: python
python:
  - "3.5"
  - "3.6"

env:
  - TOXENV=py

cache: pip

install:
  - pip install -U codecov tox

script:
  - python setup.py test

after_success:
  - codecov

branches:
  only:
    - master
